
package de.htwg_konstanz.ebus.wholesaler.ws.order;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b59-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "OrderService", targetNamespace = "http://www.htwg-konstanz.de/ebsf/ws/order")
public class OrderService
    extends Service
{
    public OrderService(URL wsdlLocation) 
    {
        super(wsdlLocation, new QName("http://www.htwg-konstanz.de/ebsf/ws/order", "OrderService"));
    }

    /**
     * 
     * @return
     *     returns OrderServicePortType
     */
    @WebEndpoint(name = "OrderServicePort")
    public OrderServicePortType getOrderServicePort() 
    {
        return (OrderServicePortType)super.getPort(new QName("http://www.htwg-konstanz.de/ebsf/ws/order", "OrderServicePort"), OrderServicePortType.class);
    }
}

